-- MySQL Script generated by MySQL Workbench
-- Sun May 14 17:28:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pais_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais_cliente` (
  `idpais_cliente` INT NOT NULL AUTO_INCREMENT,
  `pais_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpais_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_cliente` (
  `idestado_cliente` INT NOT NULL AUTO_INCREMENT,
  `estado_cliente` VARCHAR(45) NOT NULL,
  `pais_cliente_idpais_cliente` INT NOT NULL,
  PRIMARY KEY (`idestado_cliente`),
  INDEX `fk_estado_cliente_pais_cliente1_idx` (`pais_cliente_idpais_cliente` ASC) ,
  CONSTRAINT `fk_estado_cliente_pais_cliente1`
    FOREIGN KEY (`pais_cliente_idpais_cliente`)
    REFERENCES `mydb`.`pais_cliente` (`idpais_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade_cliente` (
  `idcidade_cliente` INT NOT NULL AUTO_INCREMENT,
  `cidade_cliente` VARCHAR(45) NOT NULL,
  `estado_cliente_idestado_cliente` INT NOT NULL,
  PRIMARY KEY (`idcidade_cliente`),
  INDEX `fk_cidade_cliente_estado_cliente1_idx` (`estado_cliente_idestado_cliente` ASC) ,
  CONSTRAINT `fk_cidade_cliente_estado_cliente1`
    FOREIGN KEY (`estado_cliente_idestado_cliente`)
    REFERENCES `mydb`.`estado_cliente` (`idestado_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(45) NULL,
  `cidade_cliente_idcidade_cliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_cidade_cliente1_idx` (`cidade_cliente_idcidade_cliente` ASC) ,
  CONSTRAINT `fk_cliente_cidade_cliente1`
    FOREIGN KEY (`cidade_cliente_idcidade_cliente`)
    REFERENCES `mydb`.`cidade_cliente` (`idcidade_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modelo_carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo_carro` (
  `idmodelo_carro` INT NOT NULL AUTO_INCREMENT,
  `modelo_carro` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idmodelo_carro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anocarro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anocarro` (
  `idanocarro` INT NOT NULL AUTO_INCREMENT,
  `anocarro` INT NOT NULL,
  PRIMARY KEY (`idanocarro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marca_carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca_carro` (
  `idmarca_carro` INT NOT NULL AUTO_INCREMENT,
  `marca_carro` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idmarca_carro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carro` (
  `idcarro` INT NOT NULL AUTO_INCREMENT,
  `kmcarro` INT NOT NULL,
  `classicarro` VARCHAR(50) NOT NULL,
  `modelo_carro_idmodelo_carro` INT NOT NULL,
  `anocarro_idanocarro` INT NOT NULL,
  `marca_carro_idmarca_carro` INT NOT NULL,
  PRIMARY KEY (`idcarro`),
  INDEX `fk_carro_modelo_carro1_idx` (`modelo_carro_idmodelo_carro` ASC) ,
  INDEX `fk_carro_anocarro1_idx` (`anocarro_idanocarro` ASC) ,
  INDEX `fk_carro_marca_carro1_idx` (`marca_carro_idmarca_carro` ASC) ,
  CONSTRAINT `fk_carro_modelo_carro1`
    FOREIGN KEY (`modelo_carro_idmodelo_carro`)
    REFERENCES `mydb`.`modelo_carro` (`idmodelo_carro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carro_anocarro1`
    FOREIGN KEY (`anocarro_idanocarro`)
    REFERENCES `mydb`.`anocarro` (`idanocarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carro_marca_carro1`
    FOREIGN KEY (`marca_carro_idmarca_carro`)
    REFERENCES `mydb`.`marca_carro` (`idmarca_carro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`combustivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`combustivel` (
  `idcombustivel` INT NOT NULL AUTO_INCREMENT,
  `tipocombustivel` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idcombustivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datalocacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datalocacao` (
  `iddatalocacao` INT NOT NULL AUTO_INCREMENT,
  `datalocacao` DATETIME NOT NULL,
  PRIMARY KEY (`iddatalocacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dataentrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dataentrega` (
  `iddataentrega` INT NOT NULL AUTO_INCREMENT,
  `dataentrega` DATETIME NOT NULL,
  PRIMARY KEY (`iddataentrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_vendedor` (
  `idestado_vendedor` INT NOT NULL AUTO_INCREMENT,
  `estado_vendedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado_vendedor`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendedor` (
  `idvendedor` INT NOT NULL AUTO_INCREMENT,
  `nome_vendedor` VARCHAR(15) NOT NULL,
  `sexo_vendedor` SMALLINT NOT NULL,
  `estado_vendedor_idestado_vendedor` INT NOT NULL,
  PRIMARY KEY (`idvendedor`),
  INDEX `fk_vendedor_estado_vendedor1_idx` (`estado_vendedor_idestado_vendedor` ASC),
  CONSTRAINT `fk_vendedor_estado_vendedor1`
    FOREIGN KEY (`estado_vendedor_idestado_vendedor`)
    REFERENCES `mydb`.`estado_vendedor` (`idestado_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locacao` (
  `idlocacao` INT NOT NULL AUTO_INCREMENT,
  `horalocacao` TIME NULL,
  `qtddiaria` INT NULL,
  `vlrdiaria` DECIMAL(18,2) NULL,
  `horaentrega` VARCHAR(45) NULL,
  `datalocacao_iddatalocacao` INT NOT NULL,
  `dataentrega_iddataentrega` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  `vendedor_idvendedor` INT NOT NULL,
  `carro_idcarro` INT NOT NULL,
  `combustivel_idcombustivel` INT NOT NULL,
  PRIMARY KEY (`idlocacao`),
  INDEX `fk_locacao_datalocacao1_idx` (`datalocacao_iddatalocacao` ASC) ,
  INDEX `fk_locacao_dataentrega1_idx` (`dataentrega_iddataentrega` ASC) ,
  INDEX `fk_locacao_cliente1_idx` (`cliente_idCliente` ASC) ,
  INDEX `fk_locacao_vendedor1_idx` (`vendedor_idvendedor` ASC) ,
  INDEX `fk_locacao_carro1_idx` (`carro_idcarro` ASC) ,
  INDEX `fk_locacao_combustivel1_idx` (`combustivel_idcombustivel` ASC) ,
  CONSTRAINT `fk_locacao_datalocacao1`
    FOREIGN KEY (`datalocacao_iddatalocacao`)
    REFERENCES `mydb`.`datalocacao` (`iddatalocacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_dataentrega1`
    FOREIGN KEY (`dataentrega_iddataentrega`)
    REFERENCES `mydb`.`dataentrega` (`iddataentrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_vendedor1`
    FOREIGN KEY (`vendedor_idvendedor`)
    REFERENCES `mydb`.`vendedor` (`idvendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_carro1`
    FOREIGN KEY (`carro_idcarro`)
    REFERENCES `mydb`.`carro` (`idcarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_combustivel1`
    FOREIGN KEY (`combustivel_idcombustivel`)
    REFERENCES `mydb`.`combustivel` (`idcombustivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
